NDefines.NAI.GENERATE_WARGOAL_THREAT_BASELINE = 0.0
NDefines.NAI.DIPLOMACY_CREATE_FACTION_FACTOR = 0.75
NDefines.NDiplomacy.TENSION_SIZE_FACTOR = 0.2
NDefines.NDiplomacy.WARGOAL_JUSTIFY_TENSION_FROM_PRODUCTION = 30
NDefines.NDiplomacy.TENSION_TIME_SCALE_MONTHLY_FACTOR = -0.005
NDefines.NDiplomacy.TENSION_DECAY = 0.2
NDefines.NPolitics.BASE_LEADER_TRAITS = 3
NDefines.NCountry.BASE_RESEARCH_SLOTS = 2